### PR TITLE
Allow support for python3 strings.

### PR DESCRIPTION
**Pull request by bitfort**
I tested this in python3... but it may need to be tested in a python 2.7 env.

### CODE REVIEW

**Comment by bitfort** [comment]
Let me know if there is a better way to solve this problem, I'm not very pythony.

**Comment by tfboyd** [comment]
Keep in mind I only use python2  Let me make time to pull this down and test.

**Comment by tfboyd** [comment]
I will try this fix which I think is better

`from six import u as unicode`

**Comment by tfboyd** [comment]
fixed with
 https://github.com/tfboyd/benchmark_harness/pull/66

**Pull request closed without merging**
